[package]
name = "input"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
cortex-m.workspace = true
idol-runtime.workspace = true
jefe-api = { path = "../../lib/jefe-api" }
keyboard = { path = "../../lib/keyboard" }
input-api = { path = "../../lib/input-api" }
wireless-api = { path = "../../lib/wireless-api" }
num-traits.workspace = true
usb-api = { path = "../../lib/usb-api" }
userlib.workspace = true
util = { path = "../../lib/util" }
zerocopy.workspace = true
zerocopy-derive.workspace = true

[build-dependencies]
build-util.workspace = true
idol.workspace = true

[[bin]]
name = "input"
test = false
bench = false
