name = "q65-max"
target = "thumbv7em-none-eabihf"
board = "q65-max"
chip = "../../chips/stm32f401"
stacksize = 1024

[kernel]
name = "kernel"
requires = { flash = 24576, ram = 4096 }

[tasks.jefe]
name = "jefe"
priority = 0
start = true
stacksize = 512
max-sizes = { flash = 4096, ram = 1024 }
uses = ["reboot-flag"]
notifications = ["fault"]

[tasks.usb]
name = "usb"
priority = 1
start = true
stacksize = 1024
max-sizes = { flash = 16384, ram = 4096 }
uses = ["usb", "gpioa"]
notifications = ["usb-irq"]
interrupts = { "usb.irq" = "usb-irq" }

[tasks.spi]
name = "spi"
priority = 3
start = true
stacksize = 1024
max-sizes = { flash = 8192, ram = 2048 }
uses = ["spi1", "gpioa", "gpiob"]

[tasks.input]
name = "input"
priority = 2
start = true
stacksize = 4096
max-sizes = { flash = 16384, ram = 8192 }
uses = ["gpio"]
task-slots = ["jefe", "usb"]
notifications = ["timer"]

[tasks.rgb]
name = "rgb"
priority = 4
start = true
stacksize = 4096
max-sizes = { flash = 8192, ram = 8192 }
uses = ["gpiob"]
task-slots = ["usb", "input", "spi"]

[tasks.idle]
name = "idle"
priority = 5
start = true
stacksize = 256
max-sizes = { flash = 256, ram = 256 }
