[package]
name = "wireless"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
idol-runtime.workspace = true
num-traits.workspace = true
stm32f4.workspace = true
spi-api = { path = "../../lib/spi-api" }
wireless-api = { path = "../../lib/wireless-api" }
lkbt51 = { path = "../../lib/lkbt51" }
userlib.workspace = true
zerocopy.workspace = true
zerocopy-derive.workspace = true

[build-dependencies]
build-util.workspace = true
idol.workspace = true

[[bin]]
name = "wireless"
test = false
bench = false
